### PR TITLE
enable GitHub Actions build matrix

### PR DESCRIPTION
**Pull request by sullis**
https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs

### CODE REVIEW

**Comment by sullis** [comment]
PTAL @metlos

**Review by metlos — APPROVED** [review]
Nice!

**Comment by sullis** [comment]
I just pushed a fix to the workflow.  Please trigger the workflow again.

**Comment by metlos** [comment]
Thanks for this!

**Pull request merged**
