### PR TITLE
Do not skip transformed difference in cases of multiple transformers.

### PR DESCRIPTION
**Pull request by MishaDemianenko**
In the case when the configuration had multiple transformers it was possible
to skip transformed difference in case if any transformer
after actually transforming transformer returns null as the difference.
A described situation can happen, for example, in the case when the configuration has
SemverIgnoreTransformer and ClassificationTransfromer defined.

This PR also fixes a bug in classification-schema.json where `BINARY` value was incorrectly described.

### CODE REVIEW

**Comment by MishaDemianenko** [comment]
Example of problematic configuration:
```xml
<analysisConfiguration>
    ....
    <revapi.reclassify>
        <item>
            <code>java.class.added</code>
            <classify>
                <BINARY>BREAKING</BINARY>
                <SOURCE>BREAKING</SOURCE>
            </classify>
        </item>
    </revapi.reclassify>
    <revapi.semver.ignore>
        <enabled>true</enabled>
        <versionIncreaseAllows>
            <major>breaking</major>
            <minor>nonBreaking</minor>
            <patch>equivalent</patch>
        </versionIncreaseAllows>
        <passThroughDifferences>
            <item>java.class.nonPublicPartOfAPI</item>
        </passThroughDifferences>
    </revapi.semver.ignore>
   .....
</analysisConfiguration>
```

**Comment by metlos** [comment]
This is kind of a chicken-egg problem, IMHO, with no clear winning solution.

The current implementation prioritizes the disappearance of the differences if some transforms think so, while your change prioritizes the transformation over disappearance.

The prioritization of disappearance is good in situations where you don't want to consider the differences for further transformations. For example, adding an annotation attribute method to an annotation type is originally reported as `java.method.added` and then transformed into either `java.method.attributeWithNoDefaultAddedToAnnotationType` or `java.method.attributeWithDefaultAddedToAnnotationType` depending on further analysis by the transformer.

If you wanted to ignore all added methods, prioritizing the removal of `java.method.added` over the transformations makes a single ignore rule work also for the annotation methods.

On the other hand, with your change, if user wanted to ignore `java.method.added` they would still get the problems on the annotation attributes.

I'm not 100% sure which one is better, but I'm starting to lean towards your solution, because then the user still has an option to add additional ignore rules if need be. With the current eager removal, the impl is prone to the problem you reported.

Do you have some other thoughts on why either of the approaches is right/wrong?

**Comment by MishaDemianenko** [comment]
Hi @metlos. Thx for your answer.
We have a situation where a set of transformers can either transform or ignore some difference.
Any transformer operates on top of the current difference object and for the cases where difference transformed later decision of ignoring it can be wrong and result of that transformation should be revalidated/reevaluated to be sure that it still can be ignored or should be processed differently.

Also as you already mentioned if you want to ignore later on any of your transformations result you can add ignore rules.

**Comment by MishaDemianenko** [comment]
@metlos thx!

**Comment by metlos** [comment]
Спасибі!

**Pull request merged**
